/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package miprimeragui;

import javax.swing.JOptionPane;

/**
 *
 * @author Capacitaciones_pc30
 */
public class FrmMiPrimerClick extends javax.swing.JFrame {

    /**
     * Creates new form MiPrimerClick
     */
    public FrmMiPrimerClick() {
        initComponents();
        lblMostrarMensaje.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnPresioname = new javax.swing.JButton();
        btnPresionameMas = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtMiPrimerTexto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lblMiPrimeraAsignacion = new javax.swing.JLabel();
        btnMensajito = new javax.swing.JButton();
        lblMostrarMensaje = new javax.swing.JLabel();
        btnPresionameSiQuieresVer = new javax.swing.JButton();
        btnComprobandoConfirmDialog = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Presiona el boton:");

        btnPresioname.setText("Presioname!");
        btnPresioname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPresionameActionPerformed(evt);
            }
        });

        btnPresionameMas.setText("PresionameMas!");
        btnPresionameMas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPresionameMasActionPerformed(evt);
            }
        });

        jLabel2.setText("Digita algo en el campo de texto:");

        txtMiPrimerTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMiPrimerTextoActionPerformed(evt);
            }
        });

        jLabel3.setText("Usted digito: ");

        lblMiPrimeraAsignacion.setText("...");

        btnMensajito.setText("Mostrar Mensaje");
        btnMensajito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMensajitoActionPerformed(evt);
            }
        });

        lblMostrarMensaje.setText("............");

        btnPresionameSiQuieresVer.setText("Presioname si quieres ver");
        btnPresionameSiQuieresVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPresionameSiQuieresVerActionPerformed(evt);
            }
        });

        btnComprobandoConfirmDialog.setText("Comprobando el ConfirmDialog");
        btnComprobandoConfirmDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprobandoConfirmDialogActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnPresionameMas)
                            .addComponent(btnPresioname)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(btnMensajito)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblMiPrimeraAsignacion)))
                        .addGap(18, 18, 18)
                        .addComponent(txtMiPrimerTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnComprobandoConfirmDialog)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnPresionameSiQuieresVer)
                                .addGap(28, 28, 28)
                                .addComponent(lblMostrarMensaje)))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnPresioname))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPresionameMas)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMiPrimerTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMensajito)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblMiPrimeraAsignacion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPresionameSiQuieresVer)
                    .addComponent(lblMostrarMensaje))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnComprobandoConfirmDialog)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPresionameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPresionameActionPerformed
        JOptionPane.showMessageDialog(null, "Mi primer Mensajito y mi primer clic");
    }//GEN-LAST:event_btnPresionameActionPerformed

    private void btnPresionameMasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPresionameMasActionPerformed
        JOptionPane.showMessageDialog(null, "Este es mi primer titulo", "Este es mi primer titulito de Informacion", JOptionPane.INFORMATION_MESSAGE);
        JOptionPane.showMessageDialog(null, "Este es mi primer titulo", "Este es mi primer titulito de Alerta", JOptionPane.WARNING_MESSAGE);
        JOptionPane.showMessageDialog(null, "Este es mi primer titulo", "Este es mi primer titulito de Error", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_btnPresionameMasActionPerformed

    private void txtMiPrimerTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMiPrimerTextoActionPerformed
        lblMiPrimeraAsignacion.setText(txtMiPrimerTexto.getText());
    }//GEN-LAST:event_txtMiPrimerTextoActionPerformed

    private void btnMensajitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMensajitoActionPerformed
        lblMiPrimeraAsignacion.setText(txtMiPrimerTexto.getText());
        JOptionPane.showMessageDialog(null, "Usted digito: "+txtMiPrimerTexto.getText());
    }//GEN-LAST:event_btnMensajitoActionPerformed

    private void btnPresionameSiQuieresVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPresionameSiQuieresVerActionPerformed
        if (txtMiPrimerTexto.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Digita algo en el campo de texto", "Mensaje de advertencia", JOptionPane.WARNING_MESSAGE);
        }else{
            lblMostrarMensaje.setText(txtMiPrimerTexto.getText());
            lblMostrarMensaje.setVisible(true);  
        }
    }//GEN-LAST:event_btnPresionameSiQuieresVerActionPerformed

    private void btnComprobandoConfirmDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprobandoConfirmDialogActionPerformed
        int opcion=JOptionPane.showConfirmDialog(null, "Desea continuar");
        switch (opcion){
            case 0:
                JOptionPane.showMessageDialog(null, "Usted Selecciono Si");
                break;
            case 1:
                JOptionPane.showMessageDialog(null, "Usted Selecciono No");
                break;
            case 2:
                JOptionPane.showMessageDialog(null, "Usted Selecciono Cancelar");
                break;
        }
    }//GEN-LAST:event_btnComprobandoConfirmDialogActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMiPrimerClick.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMiPrimerClick.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMiPrimerClick.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMiPrimerClick.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMiPrimerClick().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComprobandoConfirmDialog;
    private javax.swing.JButton btnMensajito;
    private javax.swing.JButton btnPresioname;
    private javax.swing.JButton btnPresionameMas;
    private javax.swing.JButton btnPresionameSiQuieresVer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblMiPrimeraAsignacion;
    private javax.swing.JLabel lblMostrarMensaje;
    private javax.swing.JTextField txtMiPrimerTexto;
    // End of variables declaration//GEN-END:variables
}
